### ISSUE TITLE
Pref array printing when using E107.org copy of the plugin 

### ISSUE THREAD

**Issue by Serios** [G4HDU-plugins/gotop#1]
When plugin is downloaded from e107.org there is minor bug causing all plugin pref to be listed on Admin and Front end areas. In e_header.php line 83 there is 
`print_a(self::$gotopPrefs);`
which is not commented (maybe dev leftover), causing this bug. It is quick and easy fix to add // infront

**Comment by LaocheXe** [comment]
![capture2](https://user-images.githubusercontent.com/5818022/33108109-2bc6e948-cf00-11e7-95ad-9b7b5f831ffd.JPG)
